#!/usr/bin/env python3
"""Generate SKILL.md files from SKILL.md.tmpl templates.

Resolves {{PLACEHOLDER}} tokens using the resolver registry and writes
auto-generated SKILL.md files. Source of truth is always the .tmpl file.

Usage:
    python3 scripts/gen_skills.py              # generate all SKILL.md files
    python3 scripts/gen_skills.py --dry-run    # check freshness (exit 1 if stale)
    python3 scripts/gen_skills.py --report     # print token budget per skill
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Callable

# Resolve kit root (parent of scripts/)
KIT_ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = KIT_ROOT / "skills"
PACKS_DIR = KIT_ROOT / "packs"

HEADER = "<!-- AUTO-GENERATED by scripts/gen_skills.py — DO NOT EDIT. Edit SKILL.md.tmpl instead. -->\n"

# ---------------------------------------------------------------------------
# Resolver registry
# ---------------------------------------------------------------------------

# Import preamble generator
sys.path.insert(0, str(KIT_ROOT / "scripts"))
from preambles import generate_preamble  # noqa: E402

# Wrapper-script based commands. Each placeholder resolves to a single
# prefix-matchable command so Claude Code's permission matcher can safely
# allowlist them (Bash(bash scripts/<name>.sh *)) without granting Bash(*).
# Avoid compound commands, command substitution, and redirections here —
# those live inside the wrapper scripts themselves.
CHECKPOINT_CMD = "bash scripts/checkpoint.sh"

WORKTREE_SETUP = 'WT="$(bash scripts/wt_setup.sh <branch>)"'

WORKTREE_CLEANUP = "bash scripts/wt_cleanup.sh <branch>"

REGISTRY_UPDATE = (
    "bash scripts/registry_edit.sh issues.md -- bash -c '<update command>'"
)


def _resolve_preamble(skill_name: str) -> str:
    return generate_preamble(skill_name)


def _resolve_checkpoint_cmd(_skill_name: str) -> str:
    return CHECKPOINT_CMD


def _resolve_worktree_setup(_skill_name: str) -> str:
    return WORKTREE_SETUP


def _resolve_worktree_cleanup(_skill_name: str) -> str:
    return WORKTREE_CLEANUP


def _resolve_registry_update(_skill_name: str) -> str:
    return REGISTRY_UPDATE


RESOLVERS: dict[str, Callable[[str], str]] = {
    "PREAMBLE": _resolve_preamble,
    "CHECKPOINT_CMD": _resolve_checkpoint_cmd,
    "WORKTREE_SETUP": _resolve_worktree_setup,
    "WORKTREE_CLEANUP": _resolve_worktree_cleanup,
    "REGISTRY_UPDATE": _resolve_registry_update,
}

# ---------------------------------------------------------------------------
# Template processing
# ---------------------------------------------------------------------------


def discover_templates() -> list[Path]:
    """Find all SKILL.md.tmpl files under skills/ AND packs/<name>/skills/.

    Core skills live at the top level; pack skills (e.g., sales) live under
    packs/<pack-name>/skills/<skill-name>/SKILL.md.tmpl. Both surfaces are
    walked so a single `gen_skills.py` invocation regenerates everything.
    """
    templates = list(SKILLS_DIR.glob("*/SKILL.md.tmpl"))
    if PACKS_DIR.is_dir():
        templates.extend(PACKS_DIR.glob("*/skills/*/SKILL.md.tmpl"))
    return sorted(templates)


def extract_skill_name(tmpl_path: Path) -> str:
    """Extract skill name from template path (parent directory name)."""
    return tmpl_path.parent.name


def process_template(tmpl_path: Path) -> str:
    """Read a template and resolve all {{PLACEHOLDER}} tokens."""
    content = tmpl_path.read_text(encoding="utf-8")
    skill_name = extract_skill_name(tmpl_path)

    def replace_fn(match: re.Match) -> str:
        token = match.group(1)
        resolver = RESOLVERS.get(token)
        if resolver is None:
            try:
                rel = tmpl_path.relative_to(KIT_ROOT)
            except ValueError:
                rel = tmpl_path
            raise ValueError(
                f"Unknown placeholder {{{{{token}}}}} in {rel}"
            )
        return resolver(skill_name)

    resolved = re.sub(r"\{\{(\w+)\}\}", replace_fn, content)

    # Validate no unresolved placeholders remain
    remaining = re.findall(r"\{\{(\w+)\}\}", resolved)
    if remaining:
        raise ValueError(
            f"Unresolved placeholders in {tmpl_path.relative_to(KIT_ROOT)}: {remaining}"
        )

    return HEADER + resolved


def output_path(tmpl_path: Path) -> Path:
    """Compute the output SKILL.md path from a template path."""
    return tmpl_path.parent / "SKILL.md"


# ---------------------------------------------------------------------------
# CLI modes
# ---------------------------------------------------------------------------


def generate_all() -> None:
    """Generate all SKILL.md files from templates."""
    templates = discover_templates()
    if not templates:
        print("No SKILL.md.tmpl files found.", file=sys.stderr)
        sys.exit(1)

    for tmpl in templates:
        content = process_template(tmpl)
        out = output_path(tmpl)
        out.write_text(content, encoding="utf-8")
        skill = extract_skill_name(tmpl)
        print(f"  generated: skills/{skill}/SKILL.md")

    print(f"\n{len(templates)} skills generated.")


def dry_run() -> bool:
    """Check if all generated files are fresh. Returns True if all fresh."""
    templates = discover_templates()
    stale: list[str] = []

    for tmpl in templates:
        expected = process_template(tmpl)
        out = output_path(tmpl)
        skill = extract_skill_name(tmpl)

        if not out.exists():
            stale.append(f"skills/{skill}/SKILL.md (missing)")
            continue

        actual = out.read_text(encoding="utf-8")
        if actual != expected:
            stale.append(f"skills/{skill}/SKILL.md (stale)")

    if stale:
        print("Stale SKILL.md files detected:", file=sys.stderr)
        for s in stale:
            print(f"  {s}", file=sys.stderr)
        print(
            "\nRun `python3 scripts/gen_skills.py` to regenerate.",
            file=sys.stderr,
        )
        return False

    print(f"All {len(templates)} SKILL.md files are fresh.")
    return True


def report() -> None:
    """Print token budget report for each skill."""
    templates = discover_templates()

    print(f"{'Skill':<20} {'Lines':>6} {'Est. Tokens':>12}")
    print("-" * 40)

    total_lines = 0
    total_tokens = 0

    for tmpl in templates:
        content = process_template(tmpl)
        lines = content.count("\n")
        # Rough estimate: ~5 tokens per line (avg line ~20 chars, ~4 chars/token)
        tokens = int(lines * 5)
        skill = extract_skill_name(tmpl)
        print(f"{skill:<20} {lines:>6} {tokens:>12}")
        total_lines += lines
        total_tokens += tokens

    print("-" * 40)
    print(f"{'TOTAL':<20} {total_lines:>6} {total_tokens:>12}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate SKILL.md files from templates."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Check freshness without writing. Exit 1 if stale.",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="Print token budget per skill.",
    )
    args = parser.parse_args()

    if args.dry_run:
        ok = dry_run()
        sys.exit(0 if ok else 1)
    elif args.report:
        report()
    else:
        generate_all()


if __name__ == "__main__":
    main()
